{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-azure-storage
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName | default "azure-key-vault" }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-azure-storage
    creationPolicy: Owner
  data:
    - secretKey: azurestorageaccountname
      remoteRef:
        key: storage-account-name
    - secretKey: azurestorageaccountkey
      remoteRef:
        key: storage-account-key
{{- range .Values.externalSecrets.additionalSecrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
{{- end }}
{{- end }}
