apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    {{- include "demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: TITLE
              value: {{ .Values.worker.env.TITLE | quote }}
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.service.port }}"
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          {{- if .Values.worker.storage.enabled }}
          volumeMounts:
            - name: shared-data
              mountPath: {{ .Values.worker.storage.mountPath }}
          {{- end }}
      {{- if .Values.worker.storage.enabled }}
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ if .Values.worker.storage.existingClaim }}{{ .Values.worker.storage.existingClaim }}{{ else }}{{ .Release.Name }}-api-data{{ end }}
      {{- end }}
