chart_version: 0.10.7
delimiter: '-'
environment: ue2
label_order:
  - namespace
  - environment
  - stage
  - name
  - attributes
namespace: homelab
regex_replace_chars: /[^a-zA-Z0-9-]/
region: eastus2
service_account_name: external-secrets-sa
stage: dev
tags:
  ManagedBy: Atmos
  Project: homelab-aks
tenant: null
